version: "3.5"
services:
  web:
    image: nginx      
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80     
    depends_on:
      - app
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: post9879523465
    ports:
      - 5432
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails_app:/rails_app
    env_file:
      - .env    
    ports:
      - 3000:3000  
    depends_on:
      - db
